# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a24f3111f4321b6f6a39dc282afca3c5bdf4c42299e02bed11014c820e23c26a4738ba3139914504b5406ccdc1831e08d9c0512f27834bbc812c4a7c8ca1874

test:
  secret_key_base: 53ab9550d67291ea0bf9669474052b0da21f081d039556f606427ebf80879499fa9be089fad4685f561dc755595db6011a818b8de843a966367cf338fd0dd6e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
